version: "3.7"

x-app: &api-app
  build:
    context: ./api
  env_file: ./api/.env
  depends_on:
    - db
    - kvs
    - minio
  environment:
    DB_HOST: db
    DB_USER: postgres
    DB_PASSWORD: password
    KVS_HOST: kvs
    SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
    AWS_REGION: ${AWS_REGION}
    AWS_BUCKET: ${AWS_BUCKET}
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    API_CORS_ALLOW_ORIGIN: $API_CORS_ALLOW_ORIGIN
    MINIO_ENDPOINT: ${MINIO_ENDPOINT}
    MAINTENANCE_MODE: ${MAINTENANCE_MODE}
  volumes:
    - .:/api/app:cached
    - gem-local:/usr/local/bundle
    - /api/app/tmp
    - ./tmp/letter_opener:/api/app/tmp/letter_opener
    - type: bind
      source: /run/host-services/ssh-auth.sock
      target: /run/host-services/ssh-auth.sock

services:
  db:
    image: postgres:14.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-local:/var/lib/postgresql/data
  kvs:
    image: redis:6.0
    volumes:
      - kvs-local:/data
  web:
    <<: *api-app
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
  worker:
    <<: *api-app
    depends_on:
      - web
    command: bundle exec sidekiq
  minio:
    image: minio/minio:latest
    environment:
      MINIO_REGION_NAME: ${AWS_REGION}
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
      MINIO_API_CORS_ALLOW_ORIGIN: $API_CORS_ALLOW_ORIGIN
      MINIO_DOMAIN: localhost
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data-local:/data
      - minio-config-local:/root/.minio
    command: server /data --console-address :9001
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio $MINIO_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY) do echo ...waiting... && sleep 1; done;
      /usr/bin/mc mb --region $AWS_REGION myminio/$AWS_BUCKET;
      /usr/bin/mc policy set public myminio/$AWS_BUCKET;
      exit 0;
      "

volumes:
  gem-local:
    driver: "local"
  db-local:
    driver: "local"
  kvs-local:
    driver: "local"
  minio-data-local:
    driver: "local"
  minio-config-local:
    driver: "local"
